### ISSUE TITLE
huge slog data:... URL in stack trace

### ISSUE THREAD

**Issue by dckc** [agoric-labs/jessica#36]
@michaelfig any idea why this huge data URL is in the stack track or how to get rid of it?

```
error: Syntax error at 752 "m" #0:752 Error
    at /home/connolly/projects/js2rho/node_modules/@michaelfig/slog/dist/slog.cjs.js:118:25
    at Function.tag [as error] (/home/connolly/projects/js2rho/node_modules/@michaelfig/slog/dist/slog.cjs.js:69:20)
    at /home/connolly/projects/js2rho/lib/vendor/jessica/lib/boot-peg.js:88:13
    at Object.start (data:%20%20%20%20(function(act_0%2C% .... VERY VERY LONG DATA URL
```

https://gist.github.com/dckc/416bf86bc11b8e052b20daff95018a7f

**Comment by michaelfig** [comment]
I think the problem is with some `sourceURL` (or missing `sourceURL`) in an evaled string.  Hope that's enough to help you out.

While I love jessica, I need to let her fend for herself until I can devote more attention.  There's a lot of things about jessica that were just me learning my way around JS+TypeScript.  I'm better now.  Really. 😝

**Comment by dckc** [comment]
Cool. Thanks
